version: '3.6'
services:
  postgresql:
    image: 'postgres:10.4'
    container_name: postgredb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5050:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=burger
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
volumes:
  postgres-data:
